### ISSUE TITLE
About the order of axes in the 3D images

### ISSUE THREAD

**Issue by HanshengGUO** [Yicong-Li/WASPSYN23#2]
Hi,

I found annotaions of both Presynaptic T-bar and Postsynaptic sites are points in [z, y, x]. I would like to double check the order of axes in the 3D images. It's 3D numpy Array and is it in ordering like **image[x][y][z]** or **image[z][y][x]**?

Thanks again and looking forward to hearing from you!

**Comment by Yicong-Li** [comment]
The image volumes also follow the zyx order.
